spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imagegallery
    username: root
    password: sesame80
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        web: DEBUG