spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true  
#  sql:
#    init:
#      platform: h2
#  autoconfigure:
#    exclude:
#      - org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration
#      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
#      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
#        
#
#logging:
#  level:
#    org:
#      springframework:
#        web: TRACE
        
  
        