insert into seller(username) values ('jprovan@skillstorm.com');
insert into seller(username) values ('ebecerra@skillstorm.com');
insert into seller(username) values ('plee@skillstorm.com');
insert into seller(username) values ('dguerraperez@skillstorm.com');
insert into seller(username) values ('jhenry@skillstorm.com');
insert into seller(username) values ('dbehrig@skillstorm.com');

insert into listing_coupon (coupon_code, dollar_off, percent_off, discount_amount, seller_id) values ('50OFF', false, true, 50, 'dbehrig@skillstorm.com');
insert into listing_coupon (coupon_code, dollar_off, percent_off, discount_amount, seller_id) values ('5OFF', true, false, 5, 'dbehrig@skillstorm.com');

insert into LISTING_COUNTRY (COUNTRY_NAME, DEFAULT_LANGUAGE_CODE) values ('United States', 'en-US');
insert into LISTING_COUNTRY (COUNTRY_NAME, DEFAULT_LANGUAGE_CODE) values ('United Kingdom', 'en-GB');
insert into LISTING_COUNTRY (COUNTRY_NAME, DEFAULT_LANGUAGE_CODE) values ('Mexico', 'es-MX');
insert into LISTING_COUNTRY (COUNTRY_NAME, DEFAULT_LANGUAGE_CODE) values ('Japan', 'ja-JP');
insert into LISTING_COUNTRY (COUNTRY_NAME, DEFAULT_LANGUAGE_CODE) values ('Germany', 'de-DE');
insert into LISTING_COUNTRY (COUNTRY_NAME, DEFAULT_LANGUAGE_CODE) values ('France', 'fr-FR');
insert into LISTING_COUNTRY (COUNTRY_NAME, DEFAULT_LANGUAGE_CODE) values ('China', 'zh-CN');
insert into LISTING_COUNTRY (COUNTRY_NAME, DEFAULT_LANGUAGE_CODE) values ('Russia', 'ru-RU');

insert into listing_category (listing_category_name, listing_category_description) values ('Garden', 'Enable your green thumb.');
insert into listing_category (listing_category_name, listing_category_description) values ('Industrial', 'Heavy metal and machinery.');
insert into listing_category (listing_category_name, listing_category_description) values ('Movies', 'Its morbin time.');
insert into listing_category (listing_category_name, listing_category_description) values ('Tools', 'Do more faster and better.');
insert into listing_category (listing_category_name, listing_category_description) values ('Sports', 'For the active adult.');
insert into listing_category (listing_category_name, listing_category_description) values ('Health', 'Pamper yourself.');
insert into listing_category (listing_category_name, listing_category_description) values ('Books', 'Why use many word when few word do trick?');
insert into listing_category (listing_category_name, listing_category_description) values ('Jewelry', 'Bling!');
insert into listing_category (listing_category_name, listing_category_description) values ('Electronics', 'VCRs and record players.');
insert into listing_category (listing_category_name, listing_category_description) values ('Clothing', 'Like the way you look.');
insert into listing_category (listing_category_name, listing_category_description) values ('Beauty', 'Like the way you look v2.');
insert into listing_category (listing_category_name, listing_category_description) values ('Computers', 'Build your masterpiece.');
insert into listing_category (listing_category_name, listing_category_description) values ('Automotive', 'Zoom zoom.');
insert into listing_category (listing_category_name, listing_category_description) values ('Games', 'For the l33t gamerz.');
insert into listing_category (listing_category_name, listing_category_description) values ('Outdoors', 'Get lost.');

-- en-US
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, safety_information, warranty_information, weight_description) 
values ('638cc430-511a-490f-93be-48ee957bf731', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.
Fusce consequat. Nulla nisl. Nunc nisl.', '04 x 43 x 84 inches', 'Glass', '2019-02-18', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.
Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.
Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '31 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, safety_information, warranty_information, weight_description) 
values ('af7723dd-aadc-447f-8036-0b86f3d218ba', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.
Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.
In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '42 x 36 x 06 inches', 'Plexiglass', '2003-08-24', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.
Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.
Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '31 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, 
release_date, safety_information, warranty_information, weight_description) 
values ('65c09711-d0d8-4259-bea4-9a2b0aba30fa', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '78 x 86 x 26 inches', 'Rubber', '2014-06-20', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.
Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.
Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '69 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('f0e3ad74-bfc6-48b1-a0a7-8a9d96ae3455', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '73 x 92 x 43 inches', 'Wood', '2014-05-26', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.
Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '11 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('47c47812-18e2-4360-9612-c0589ca97baa', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.
Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '32 x 15 x 10 inches', 'Granite', '2004-07-14', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.
Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '08 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('d9acfb43-011a-4559-8020-bac0aa81e45e', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.
Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.
Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '15 x 75 x 12 inches', 'Plastic', '2021-06-02', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.
Fusce consequat. Nulla nisl. Nunc nisl.', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.
Phasellus in felis. Donec semper sapien a libero. Nam dui.', '25 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('ac66c7b1-1113-4d54-810c-da519769effe', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.
Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.
Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '25 x 90 x 91 inches', 'Glass', '2011-11-18', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.
In congue. Etiam justo. Etiam pretium iaculis justo.
In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '32 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('c26053ff-a9db-4ea1-accf-aa9c7f420764', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.
Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '33 x 69 x 51 inches', 'Wood', '2015-09-02', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.
Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '48 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('2e24a80b-1bcf-49dd-a2b1-93f11f8db380', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.
Phasellus in felis. Donec semper sapien a libero. Nam dui.
Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '81 x 09 x 94 inches', 'Brass', '2002-04-17', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.
Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.
Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.
Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '71 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('43d13805-28b7-4b81-8885-d0a873091b96', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.
Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '83 x 30 x 06 inches', 'Brass', '2011-12-20', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '89 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('137f290a-d15b-4dde-9df8-557a9b326431', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.
Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.
Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '50 x 24 x 23 inches', 'Wood', '2006-07-24', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.
Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '02 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('f8f7c800-7ee1-4c09-a48a-5f9e4599f079', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '80 x 17 x 67 inches', 'Stone', '2001-05-07', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.
In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '34 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('bdb7d0d6-856d-4c6d-8a9c-670280f434a1', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '29 x 19 x 15 inches', 'Wood', '2011-05-03', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.
Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.
Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '20 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('fc55b3c4-8243-4511-9c1a-71a50ff4fe13', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.
Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.
Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '15 x 00 x 05 inches', 'Rubber', '2003-05-02', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.
Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.
Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '11 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('3efd6250-506b-49f7-b154-36ebb28ccc81', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.
Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '86 x 56 x 14 inches', 'Plastic', '2006-02-11', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '87 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('002c9255-25fa-4c0a-bd46-0b3414c1d464', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '99 x 56 x 17 inches', 'Vinyl', '2015-11-28', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.
Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.
Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '36 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('87c44fbe-7298-45d1-9cf3-a100d37adeb1', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.
Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.
Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '60 x 89 x 54 inches', 'Plastic', '2008-02-27', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.
Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.
Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '68 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('d947f7f2-4c4c-43c9-88f4-65231fb54f1f', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.
Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.
Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '78 x 14 x 60 inches', 'Steel', '2003-07-11', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.
Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.
Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.
Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '63 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('065bace9-87f6-47ac-ab5c-11f6357e4b1d', 'In congue. Etiam justo. Etiam pretium iaculis justo.
In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '05 x 88 x 90 inches', 'Aluminum', '2003-01-04', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.
Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.
Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '76 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('ae2cd790-d5f5-490e-b76e-4b95a32398ca', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '76 x 99 x 77 inches', 'Aluminum', '2015-08-02', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.
Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '11 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('502bbe9a-3392-4410-b069-7617d63af92b', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '89 x 60 x 39 inches', 'Wood', '2011-05-26', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.
Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.
Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '68 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('b671102b-aa2b-4a46-8bb1-80c7ba7968cc', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '80 x 44 x 81 inches', 'Plastic', '2014-09-07', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.
Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '16 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('aa512ddb-d984-4648-b714-3d07874a2bb4', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.
In congue. Etiam justo. Etiam pretium iaculis justo.', '87 x 53 x 14 inches', 'Rubber', '2021-04-20', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '31 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('7ee2f75c-00da-4460-bb43-86273386c712', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.
Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '05 x 49 x 62 inches', 'Granite', '2017-05-16', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '33 pounds');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('e83e8c65-d78e-42e3-a263-dd74c103fbfc', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.
Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.
Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '06 x 71 x 93 inches', 'Steel', '2013-12-08', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.
Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.
Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '01 pounds');

-- en-GP
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('b75a628d-14b8-4816-baf8-c1ce8b9f2983', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '55 x 98 x 67 cm', 'Wood', '2013-01-05', 'N/A', 'N/A', '69 kg');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('6cc9a185-b0e3-44e7-8ad1-28a7cf8c9416', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '51 x 31 x 28 cm', 'Plexiglass', '2009-07-16', 'N/A', 'N/A', '77 kg');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('5e9ea13a-bba8-4d45-aa1b-8f150dda373f', 'Fusce consequat. Nulla nisl. Nunc nisl.
Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '96 x 27 x 21 cm', 'Plexiglass', '2013-08-24', 'N/A', 'N/A', '21 kg');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('d66900e8-899e-48d5-b922-3deafa978caf', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.
Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.
In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '88 x 59 x 36 cm', 'Aluminum', '2017-01-11', 'N/A', 'N/A', '96 kg');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('e7ce01d5-1328-40ab-aabd-1b69ac630555', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.
Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '32 x 56 x 05 cm', 'Brass', '2017-01-14', 'N/A', 'N/A', '97 kg');

-- es-MX
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('005a9f64-0a33-4186-9854-b427a174cb8e', 'Descripción genérica del producto para completar el componente para que podamos ver todo el gran trabajo que ha realizado en una interfaz de usuario tan magnífica.', '91 x 25 x 75 cm', 'Granito', '2020-07-27', ' No hay información disponible.', ' No hay información disponible.', '88 kg');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('13e35b70-36ee-4dcd-a53c-784f241952a7', 'Descripción genérica del producto para completar el componente para que podamos ver todo el gran trabajo que ha realizado en una interfaz de usuario tan magnífica.', '63 x 72 x 24 cm', 'Madera', '2004-12-25', ' No hay información disponible.', ' No hay información disponible.', '85 kg');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('c6b09ad5-bb55-46a6-a81b-a5b67e334f58', 'Descripción genérica del producto para completar el componente para que podamos ver todo el gran trabajo que ha realizado en una interfaz de usuario tan magnífica.', '22 x 96 x 46 cm', 'Aluminio', '2010-06-06', ' No hay información disponible.', ' No hay información disponible.', '62 kg');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('f1262138-1c70-43b1-af5d-19b09b70054a', 'Descripción genérica del producto para completar el componente para que podamos ver todo el gran trabajo que ha realizado en una interfaz de usuario tan magnífica.', '84 x 78 x 27 cm', 'Latón', '2019-07-21', ' No hay información disponible.', ' No hay información disponible.', '56 kg');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('4235f54c-75df-47b0-8f9e-aa87e13d32ca', 'Descripción genérica del producto para completar el componente para que podamos ver todo el gran trabajo que ha realizado en una interfaz de usuario tan magnífica.', '73 x 61 x 26 cm', 'Goma', '2003-06-12', ' No hay información disponible.', ' No hay información disponible.', '45 kg');

-- ja-JP
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('998726e5-99c6-46d3-a8b7-1f98593e2231', 'コンポーネントを埋めるための一般的な製品の説明。これにより、このようなすばらしいユーザーインターフェイスに投入したすばらしい作業をすべて確認できます。', '15 x 21 x 70 センチメートル', 'ガラス', '2008-07-25', '利用可能な情報はありません。', '利用可能な情報はありません。', '70 キログラム');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('2e04656f-49c4-4326-8a3c-a0d46ca9f10c', 'コンポーネントを埋めるための一般的な製品の説明。これにより、このようなすばらしいユーザーインターフェイスに投入したすばらしい作業をすべて確認できます。', '95 x 64 x 45 センチメートル', 'ガラス', '2020-07-21', '利用可能な情報はありません。', '利用可能な情報はありません。', '09 キログラム');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('1649cc2f-dc96-40f0-81f5-19e949d9b74c', 'コンポーネントを埋めるための一般的な製品の説明。これにより、このようなすばらしいユーザーインターフェイスに投入したすばらしい作業をすべて確認できます。', '90 x 40 x 52 センチメートル', 'アルミニウム', '2004-07-03', '利用可能な情報はありません。', '利用可能な情報はありません。', '91 キログラム');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('5d492028-03e9-49e7-9da9-c0fc9325a8e8', 'コンポーネントを埋めるための一般的な製品の説明。これにより、このようなすばらしいユーザーインターフェイスに投入したすばらしい作業をすべて確認できます。', '95 x 10 x 96 センチメートル', '真鍮', '2020-04-27', '利用可能な情報はありません。', '利用可能な情報はありません。', '90 キログラム');
insert into listing_details (listing_details_id, description, dimensions_description, product_material, release_date, 
safety_information, warranty_information, weight_description) values ('60dbe22a-bad0-4a4b-b8e7-f6b8e97f4001', 'コンポーネントを埋めるための一般的な製品の説明。これにより、このようなすばらしいユーザーインターフェイスに投入したすばらしい作業をすべて確認できます。', '09 x 02 x 80 センチメートル', 'ゴム', '2011-09-08', '利用可能な情報はありません。', '利用可能な情報はありません。', '68 キログラム');

-- en-US
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('66363238-3838-6564-2d37-3832382d3462', 'Upgradable encompassing groupware', 8.5, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Tagpad', '80 and up', 1, 'en-US', '638cc430-511a-490f-93be-48ee957bf731', 'jprovan@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('a95eabf3-17ab-4949-be24-ee23044fd33e', 'Proactive coherent application', 92.21, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Riffpedia', '66 and up', 1, 'en-US', 'af7723dd-aadc-447f-8036-0b86f3d218ba', 'jprovan@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('d3289d2f-f5e5-4606-a751-1e656f689913', 'Self-enabling multi-tasking alliance', 32.54, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Zooxo', '56 and up', 1, 'en-US', '65c09711-d0d8-4259-bea4-9a2b0aba30fa', 'jprovan@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('6b1bd3f3-b6af-458b-98b0-265c4be5c63f', 'Multi-tiered impactful process improvement', 84.45, 'http://dummyimage.com/400x400.png/cc0000/ffffff', 'Babblestorm', '82 and up', 1, 'en-US', 'f0e3ad74-bfc6-48b1-a0a7-8a9d96ae3455', 'jprovan@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('144432fe-f328-4be1-aeb4-802ee09e5680', 'Stand-alone full-range definition', 30.5, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Reallinks', '04 and up', 1, 'en-US', '47c47812-18e2-4360-9612-c0589ca97baa', 'jprovan@skillstorm.com');

insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('b42b8f37-fa98-42ac-90a1-2d8cb779713f', 'Upgradable cohesive architecture', 56.2, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Eamia', '79 and up', 1, 'en-US', 'd9acfb43-011a-4559-8020-bac0aa81e45e', 'jprovan@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('99c314e4-f086-43fb-8e15-13e4b58957a7', 'Open-architected composite groupware', 43.69, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Babblestorm', '79 and up', 1, 'en-US', 'ac66c7b1-1113-4d54-810c-da519769effe', 'jprovan@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('7fa0b82a-f97a-40c6-90a1-e27d570f817b', 'User-friendly uniform migration', 80.16, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Nlounge', '42 and up', 1, 'en-US', 'c26053ff-a9db-4ea1-accf-aa9c7f420764', 'jprovan@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('43bba5c3-dc43-4a06-bd3c-1afcda889e5e', 'Automated 24 hour productivity', 59.56, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Browsezoom', '87 and up', 1, 'en-US', '2e24a80b-1bcf-49dd-a2b1-93f11f8db380', 'ebecerra@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('420c11b6-cbe4-4296-bdbe-ec98bf40569e', 'Profound secondary approach', 22.08, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Yodo', '04 and up', 1, 'en-US', '43d13805-28b7-4b81-8885-d0a873091b96', 'ebecerra@skillstorm.com');

insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('0216d276-4e3f-46cb-a84f-29ee881733a1', 'Open-source empowering workforce', 77.37, 'http://dummyimage.com/400x400.png/cc0000/ffffff', 'Wikizz', '95 and up', 1, 'en-US', '137f290a-d15b-4dde-9df8-557a9b326431', 'ebecerra@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('3b277745-f3f0-49db-9141-4a848994f970', 'Function-based explicit challenge', 1.66, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Topicware', '65 and up', 1, 'en-US', 'f8f7c800-7ee1-4c09-a48a-5f9e4599f079', 'plee@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('843957c9-332e-43e1-aa3f-da0a4e812e23', 'Inverse 4th generation secured line', 28.62, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Shuffletag', '82 and up', 1, 'en-US', 'bdb7d0d6-856d-4c6d-8a9c-670280f434a1', 'plee@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('97383367-2d44-4fd2-8e62-913ea8fb534f', 'Open-source interactive moratorium', 57.34, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Mymm', '26 and up', 1, 'en-US', 'fc55b3c4-8243-4511-9c1a-71a50ff4fe13', 'plee@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('5b061f1a-9d97-4a1c-ad98-0edfe17283ec', 'Diverse well-modulated implementation', 98.7, 'http://dummyimage.com/400x400.png/cc0000/ffffff', 'Trunyx', '67 and up', 1, 'en-US', '3efd6250-506b-49f7-b154-36ebb28ccc81', 'plee@skillstorm.com');

insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('c21e7449-0c95-410f-9b87-d790ec052e47', 'Synergized full-range framework', 3.33, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Camido', '01 and up', 1, 'en-US', '002c9255-25fa-4c0a-bd46-0b3414c1d464', 'plee@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('b662c1e6-ab7b-49ae-966d-7bca1a3625ef', 'Customizable 3rd generation benchmark', 53.54, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Voonix', '91 and up', 1, 'en-US', '87c44fbe-7298-45d1-9cf3-a100d37adeb1', 'plee@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('e159366a-3011-4411-a24f-9814e719792b', 'Expanded interactive system engine', 18.7, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Kwinu', '46 and up', 1, 'en-US', 'd947f7f2-4c4c-43c9-88f4-65231fb54f1f', 'plee@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('f3d582af-02dc-420c-9e29-dbec5f06ce20', 'Persevering context-sensitive architecture', 89.64, 'http://dummyimage.com/400x400.png/cc0000/ffffff', 'Eazzy', '17 and up', 1, 'en-US', '065bace9-87f6-47ac-ab5c-11f6357e4b1d', 'plee@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('ad62adc1-c7cf-4d48-a88d-1ff0876dde73', 'Vision-oriented secondary algorithm', 44.0, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Fiveclub', '72 and up', 1, 'en-US', 'ae2cd790-d5f5-490e-b76e-4b95a32398ca', 'jhenry@skillstorm.com');

insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('58b4cd30-c29a-41c6-9f8e-092f128399f5', 'Progressive real-time circuit', 57.47, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Einti', '34 and up', 1, 'en-US', '502bbe9a-3392-4410-b069-7617d63af92b', 'jhenry@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('95db19ed-3295-4a04-bac9-3fd6174067b1', 'Pre-emptive demand-driven workforce', 45.3, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Fivespan', '94 and up', 1, 'en-US', 'b671102b-aa2b-4a46-8bb1-80c7ba7968cc', 'jhenry@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('c2b93ee7-daa6-4e28-9eb2-90a5744b132b', 'Up-sized grid-enabled knowledge user', 1.53, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Wordify', '65 and up', 1, 'en-US', 'aa512ddb-d984-4648-b714-3d07874a2bb4', 'dguerraperez@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('99d047b6-f6ae-4530-9841-3859e7f52a5c', 'Sharable real-time hierarchy', 24.97, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Yacero', '17 and up', 1, 'en-US', '7ee2f75c-00da-4460-bb43-86273386c712', 'dguerraperez@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('59d17a6c-5ba2-4657-bfb9-aa189dde74ed', 'Expanded multimedia encryption', 15.28, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Rhyzio', '30 and up', 1, 'en-US', 'e83e8c65-d78e-42e3-a263-dd74c103fbfc', 'dguerraperez@skillstorm.com');

-- en-GP
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('20311dba-060a-4d1f-890a-e2bbcfe40960', 'Multi-layered secondary moderator', 15.06, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Shuffletag', '00 and up', 2, 'en-GP', 'b75a628d-14b8-4816-baf8-c1ce8b9f2983', 'jhenry@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('26d113bd-f41b-423f-9a1b-ca1381ee4510', 'Decentralized national solution', 44.74, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Jabberbean', '52 and up', 2, 'en-GP', '6cc9a185-b0e3-44e7-8ad1-28a7cf8c9416', 'jhenry@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('eebc1b2f-207b-41bd-a6e1-9c551b44ef08', 'Upgradable didactic matrix', 39.98, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Buzzster', '67 and up', 2, 'en-GP', '5e9ea13a-bba8-4d45-aa1b-8f150dda373f', 'jhenry@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('a785dde1-e589-4df1-b48a-6713e29571c3', 'Team-oriented directional contingency', 98.41, 'http://dummyimage.com/400x400.png/ff4444/ffffff', 'Meevee', '31 and up', 2, 'en-GP', 'd66900e8-899e-48d5-b922-3deafa978caf', 'jhenry@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('05987bed-ff9b-4b7e-a6ea-a99b47f387fe', 'Optional neutral middleware', 93.28, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Geba', '13 and up', 2, 'en-GP', 'e7ce01d5-1328-40ab-aabd-1b69ac630555', 'jhenry@skillstorm.com');

-- es-MX
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('14b91b2d-8314-4c37-8a05-2dd95eb467fb', 'guantelete infinito con las 6 piedras', 284.99, 'http://dummyimage.com/400x400.png/cc0000/ffffff', 'Centizu', '90 y más', 3, 'es-MX', '005a9f64-0a33-4186-9854-b427a174cb8e', 'ebecerra@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('706a6d01-7c93-4af9-9d1b-fcd42df6d1c0', 'relámpago incrustado en una roca', 406.97, 'http://dummyimage.com/400x400.png/cc0000/ffffff', 'Eazzy', '70 y más', 3, 'es-MX', '13e35b70-36ee-4dcd-a53c-784f241952a7', 'ebecerra@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('42337c17-6136-4779-bb2b-dcbf100faf02', 'cerebros de programadores revueltos con queso', 136.55, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Dabtype', '58 y más', 3, 'es-MX', 'c6b09ad5-bb55-46a6-a81b-a5b67e334f58', 'ebecerra@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('e21cd26d-b999-4c66-ab66-9214b4e3a732', 'pepinillos en un frasco pequeño', 77.05, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Pixoboo', '60 y más', 3, 'es-MX', 'f1262138-1c70-43b1-af5d-19b09b70054a', 'ebecerra@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('09088a01-852f-40d1-a911-0f2eeb55f24b', 'el poder del sol en la palma de mi mano', 38.84, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Twiyo', '71 y más', 3, 'es-MX', '4235f54c-75df-47b0-8f9e-aa87e13d32ca', 'ebecerra@skillstorm.com');

-- ja-JP
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('62303518-8045-4da7-8bd7-353cff2d94ca', '高速ジェットコースターのケビンベーコン', 2173, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Minyx', '66 歳以上', 4, 'ja-JP', '998726e5-99c6-46d3-a8b7-1f98593e2231', 'dguerraperez@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('185136f5-21fc-4779-bf54-1e9c78e5d6ca', 'チタン製ヘルメットを備えた圧倒的なサムライボディアーマー', 53465, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Yodoo', '22 歳以上', 4, 'ja-JP', '2e04656f-49c4-4326-8a3c-a0d46ca9f10c', 'dguerraperez@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('66b8c022-77be-4835-ad13-93c2ac95e1f8', 'すべてのゲストのための追加のナプキン', 409, 'http://dummyimage.com/400x400.png/cc0000/ffffff', 'Photobug', '40 歳以上', 4, 'ja-JP', '1649cc2f-dc96-40f0-81f5-19e949d9b74c', 'dguerraperez@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('6b28cc34-f8fe-4822-a1ee-4f3ab6820190', '完全に安定していない本棚を構築するための合板', 8236, 'http://dummyimage.com/400x400.png/dddddd/000000', 'Linktype', '57 歳以上', 4, 'ja-JP', '5d492028-03e9-49e7-9da9-c0fc9325a8e8', 'dguerraperez@skillstorm.com');
insert into listing (listing_id, listing_title, listing_price, listing_image_src, product_brand, manufacturer_recommended_age, listed_in_country, listing_language_code, listing_details_id, username) values ('160bfc2a-1c9d-4f9d-a29c-c9731095917b', '最高級のディルで塩漬けにしたピクルスの印象的なコレクション', 81120, 'http://dummyimage.com/400x400.png/5fa2dd/ffffff', 'Bubblebox', '33 歳以上', 4, 'ja-JP', '60dbe22a-bad0-4a4b-b8e7-f6b8e97f4001', 'dguerraperez@skillstorm.com');

-- listing category mappings (some having 2, some only 1)
-- en-US
insert into listing_categories (listing_id, category_id) values ('66363238-3838-6564-2d37-3832382d3462', 1);
insert into listing_categories (listing_id, category_id) values ('a95eabf3-17ab-4949-be24-ee23044fd33e', 2);
insert into listing_categories (listing_id, category_id) values ('d3289d2f-f5e5-4606-a751-1e656f689913', 3);
insert into listing_categories (listing_id, category_id) values ('6b1bd3f3-b6af-458b-98b0-265c4be5c63f', 4);
insert into listing_categories (listing_id, category_id) values ('144432fe-f328-4be1-aeb4-802ee09e5680', 5);

-- en-GP
insert into listing_categories (listing_id, category_id) values ('20311dba-060a-4d1f-890a-e2bbcfe40960', 15);
insert into listing_categories (listing_id, category_id) values ('26d113bd-f41b-423f-9a1b-ca1381ee4510', 14);
insert into listing_categories (listing_id, category_id) values ('eebc1b2f-207b-41bd-a6e1-9c551b44ef08', 13);
insert into listing_categories (listing_id, category_id) values ('a785dde1-e589-4df1-b48a-6713e29571c3', 12);
insert into listing_categories (listing_id, category_id) values ('05987bed-ff9b-4b7e-a6ea-a99b47f387fe', 11);

-- es-MX
insert into listing_categories (listing_id, category_id) values ('14b91b2d-8314-4c37-8a05-2dd95eb467fb', 1);
insert into listing_categories (listing_id, category_id) values ('706a6d01-7c93-4af9-9d1b-fcd42df6d1c0', 2);
insert into listing_categories (listing_id, category_id) values ('42337c17-6136-4779-bb2b-dcbf100faf02', 3);
insert into listing_categories (listing_id, category_id) values ('e21cd26d-b999-4c66-ab66-9214b4e3a732', 4);
insert into listing_categories (listing_id, category_id) values ('09088a01-852f-40d1-a911-0f2eeb55f24b', 5);

-- ja-JP
insert into listing_categories (listing_id, category_id) values ('62303518-8045-4da7-8bd7-353cff2d94ca', 1);
insert into listing_categories (listing_id, category_id) values ('185136f5-21fc-4779-bf54-1e9c78e5d6ca', 3);
insert into listing_categories (listing_id, category_id) values ('66b8c022-77be-4835-ad13-93c2ac95e1f8', 5);
insert into listing_categories (listing_id, category_id) values ('6b28cc34-f8fe-4822-a1ee-4f3ab6820190', 7);
insert into listing_categories (listing_id, category_id) values ('160bfc2a-1c9d-4f9d-a29c-c9731095917b', 9);